[build]
command = "npm run build"
publish = "build"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = "./build"
entry-point = "."

[env.production]
name = "godar"
workers_dev = true
route = ""
zone_id = "" 